module_name: Siesta
author_name: Bust Out Solutions
author_url: http://bustoutsolutions.com
github_url: https://github.com/bustoutsolutions/siesta
excluded_files: [Source/Support/Siesta-ObjC.swift, Source/Support/Deprecations.swift]

copyright: '© 2015 [Bust Out Solutions](http://bustoutsolutions.com) under [open source license](https://github.com/bustoutsolutions/siesta/blob/master/LICENSE).'

swift_version: 2.1.1

custom_categories:
  - name: Resources
    children:
    - Service
    - Resource
    - Entity
    - Error
    - Configuration
    - ConfigurationPatternConvertible
    - TypedContentAccessors

  - name: Observering Resources
    children:
    - ResourceObserver
    - ResourceObserverClosure
    - ResourceEvent

  - name: Requests
    children:
    - Request
    - RequestMethod

  - name: Response Parsing
    children:
    - Response
    - ResponseTransformer
    - TransformerSequence
    - ResponseContentTransformer
    - JSONResponseTransformer(_:)
    - TextResponseTransformer(_:)
    - ImageResponseTransformer(_:)

  - name: UI Helpers
    children:
    - ResourceStatusOverlay
    - RemoteImageView

  - name: Network Layer
    children:
    - NetworkingProvider
    - NetworkingProviderConvertible
    - RequestNetworking
    - RequestNetworkingCompletionCallback
    - RequestTransferMetrics
    - NSURLSessionProvider
    - AlamofireProvider

  - name: Caching
    children:
    - EntityCache
    - EntityEncoder
    - JSONEntityEncoder

  - name: Logging
    children:
    - enabledLogCategories
    - LogCategory
    - logger
