language: objective-c
os: osx
osx_image: xcode7.1

script: |
  # ------ Certificates ------

  # Thanks to https://github.com/Carthage/Carthage/blob/12fb7881876b4987584e49d00befcd2a8b6b354d/script/cibuild#L29-L51
  # but no thanks to Carthage for refusing to do simulator-only builds that would make all these keychain shenanigans unnecessary.

  KEYCHAIN=ios-build.keychain
  local password=cibuild

  # Create a temporary keychain for code signing.

  security create-keychain -p "$password" "$KEYCHAIN"
  security default-keychain -s "$KEYCHAIN"
  security unlock-keychain -p "$password" "$KEYCHAIN"
  security set-keychain-settings -t 3600 -l "$KEYCHAIN"

  # Download the certificate for the Apple cert authority
  local certpath="/tmp/apple_wwdr.cer"
  curl 'https://developer.apple.com/certificationauthority/AppleWWDRCA.cer' > "$certpath"
  security import "$certpath" -k "$KEYCHAIN" -T /usr/bin/codesign

  # Import our development certificate.
  security import ".ios-dev-cert.p12" -k "$KEYCHAIN" -P "$KEY_PASSWORD" -T /usr/bin/codesign
  echo "Available identities after import:"
  security find-identity

  # ------ Tools ------

  set -x

  #gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  # Fix parsing bug for Swift output:
  git clone -b patch-1 https://github.com/pcantrell/xcpretty.git /tmp/xcpretty
  
  #brew update
  #brew install carthage

  # ------ Dependencies ------

  # Optional pre-download, because builds are so slow on Travis, and Carthage builds _everything_:
  echo "Downloading prebuilt dependencies"
  curl https://innig.net/tmp/siesta-deps.tar.bz2 | bzcat | tar xv

  # Uncomment to build with Carthage instead:
  #echo "Building dependencies"
  #carthage bootstrap --platform ios --verbose

  # ------ Project build (at last!) ------

  for device in 'OS=8.1,name=iPhone 4s' 'OS=9.1,name=iPhone 6'; do
    echo
    echo —————— Running tests for $device ...

    Siesta_DelayAfterEachSpec=1 \
    Siesta_TestMultipleNetworkProviders=1 \
    xcodebuild test \
        -project Siesta.xcodeproj \
        -scheme Siesta \
        -destination "platform=iOS Simulator,$device" 2>&1 \
      | /tmp/xcpretty/bin/xcpretty -c
    
    buildresult="$buildresult${PIPESTATUS[0]}"

    echo —————— Completed tests for $device.
  done

  sleep 5  # Workaround for Travis log truncation

  exit $buildresult
