title: Siesta
baseurl: "/siesta"
url: "https://bustoutsolutions.github.io"
twitter_username: teambustout
github_username:  bustoutsolutions/siesta

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "attributes", "with_toc_data"]
  with_toc_data: true
