title: Siesta
baseurl: "/siesta"
url: "https://bustoutsolutions.github.io"
twitter_usernames: [siestaframework, teambustout]
github_username:  bustoutsolutions/siesta

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
